# Site settings
email_snp: saltnpepper@lists.hu-berlin.de
email_atomic: atomic-user@listserv.uni-jena.de
baseurl: ""
url: "http://corpus-tools.github.io"
bootstrap_dist: ../bootstrap/dist
site_home: /home/index.html
site_salt: /salt/
site_salt_main: /salt/index.html
site_corpora: /corpora/
site_pepper: /pepper/
site_pepper_main: /pepper/index.html
site_annis: /annis/
site_atomic: /atomic/index.html
css_url: ../css
github_pepper: https://github.com/korpling/pepper
github_salt: https://github.com/korpling/salt
apache_license: <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>

module_paula: https://github.com/korpling/pepperModules-PAULAModules
module_annis: https://github.com/korpling/pepperModules-ANNISModules
module_exmaralda: https://github.com/korpling/pepperModules-EXMARaLDAModules
module_saltInfo: https://github.com/korpling/pepperModules-SaltInfoModules
module_tei: https://github.com/korpling/pepperModules-TEIModules

# Site settings
email: "annis-admin@ling.uni-potsdam.de"
title: "corpus-tools.org"
description: "A collection of tools for processing your linguistic data: annotation, conversion, analysis"
github_username:  korpling
publisher: Humboldt-Universit√§t zu Berlin, Friedrich Schiller University Jena

# Build settings
kramdown: 
  parse_block_html: true

gems:
  - jekyll-redirect-from
